"""Test

Revision ID: 19250b141b33
Revises: 436a7a1973e9
Create Date: 2015-05-03 21:08:20.155192

"""

# revision identifiers, used by Alembic.
revision = '19250b141b33'
down_revision = '436a7a1973e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
