"""initial migration

Revision ID: 311d9e84b68a
Revises: None
Create Date: 2015-05-03 19:33:56.984047

"""

# revision identifiers, used by Alembic.
revision = '311d9e84b68a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
