"""email added

Revision ID: 3223652c004e
Revises: 19250b141b33
Create Date: 2015-05-04 19:29:58.073671

"""

# revision identifiers, used by Alembic.
revision = '3223652c004e'
down_revision = '19250b141b33'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
