"""corrected the update

Revision ID: 4666d0ebbe59
Revises: 741f066e03c
Create Date: 2015-05-10 16:47:06.902355

"""

# revision identifiers, used by Alembic.
revision = '4666d0ebbe59'
down_revision = '741f066e03c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
