"""added confirmed field

Revision ID: 741f066e03c
Revises: 3223652c004e
Create Date: 2015-05-10 16:27:38.651715

"""

# revision identifiers, used by Alembic.
revision = '741f066e03c'
down_revision = '3223652c004e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
